### ISSUE TITLE
sid: 5002014 flowbit doesn't seem to be set

### ISSUE THREAD

**Issue by srawls1740** [beave/sagan-rules#15]
alert syslog $HOME_NET any -> $EXTERNAL_NET any (msg: "[WINDOWS-MISC] System shutdown [FLOWBIT SET]"; content: " 1074|3a| "; program: System|USER32; xbits: set, reboot.windows, 60; xbits: noalert; classtype: system-event; reference: url,wiki.quadrantsec.com/bin/view/Main/5002014; sid: 5002014; rev:7;)

The rule for "1100: The event logging service has shut down" isn't recognizing the reboot.windows flowbit.

**Comment by beave** [comment]
I think this is resolved, no?
